-- seed.sql - Datos de prueba reales para Wine-Pick-QR
-- Incluye: 1 admin, 40 productos, 20 promociones, eventos de consulta

USE wine_pick_qr;

-- =====================================================
-- admin_users (1 registro)
-- Password: Admin2026! | Hash bcrypt
-- =====================================================
INSERT INTO admin_users (username, password_hash, created_at) VALUES
('Admin', '$2y$10$tyG5oSLh/BbLarsuFEQVHe2/riIv.0yoGLulR3gLrZIUymUh0hpM2', NOW());

-- =====================================================
-- products (40 productos variados)
-- =====================================================
INSERT INTO products (
    public_code, name, drink_type, winery_distillery, varietal, origin, vintage_year,
    short_description, base_price, visible_stock, image_url, is_active, created_at, updated_at, last_modified_by_admin_id
) VALUES
('MALBEC-ALAMOS-750', 'Álamos Malbec Clásico', 'vino', 'Bodegas Álamos', 'Malbec', 'Mendoza, Argentina', 2022, 'Malbec equilibrado con notas de cereza negra y especias. Ideal para carnes rojas.', 3500.00, 25, NULL, 1, NOW(), NOW(), 1),
('PINOT-SANTA-750', 'Santa Pinot Noir Reserva', 'vino', 'Bodegas Santa', 'Pinot Noir', 'Río Negro, Argentina', 2021, 'Pinot elegante con aromas a frutas rojas frescas y taninos sedosos.', 4200.00, 18, NULL, 1, NOW(), NOW(), 1),
('CABERNET-NORTON-750', 'Norton Cabernet Sauvignon Crianza', 'vino', 'Bodegas Norton', 'Cabernet Sauvignon', 'Mendoza, Argentina', 2020, 'Cabernet de guarda con estructura compleja y final persistente.', 4800.00, 14, NULL, 1, NOW(), NOW(), 1),
('CHARDONNAY-CATENA-750', 'Catena Chardonnay', 'vino', 'Bodegas Catena', 'Chardonnay', 'Mendoza, Argentina', 2023, 'Chardonnay fresco con notas de mantequilla y frutas amarillas.', 5200.00, 20, NULL, 1, NOW(), NOW(), 1),
('SYRAH-ACHÁVAL-750', 'Achaval-Ferrer Syrah', 'vino', 'Bodegas Achaval-Ferrer', 'Syrah', 'Mendoza, Argentina', 2021, 'Syrah intenso con especias y frutos negros. Gran potencial de envejecimiento.', 6500.00, 12, NULL, 1, NOW(), NOW(), 1),
('MALBEC-SUSANA-750', 'Susana Balbo Signature Malbec', 'vino', 'Susana Balbo Wines', 'Malbec', 'Salta, Argentina', 2021, 'Malbec de altura con elegancia y frescura característica de Salta.', 6000.00, 16, NULL, 1, NOW(), NOW(), 1),
('BONARDA-LUIGI-750', 'Luigi Bosca Bonarda', 'vino', 'Luigi Bosca', 'Bonarda', 'Mendoza, Argentina', 2022, 'Bonarda jugoso y fácil de beber, perfecto para picadas.', 3000.00, 30, NULL, 1, NOW(), NOW(), 1),
('MERLOT-TOLO-750', 'Atómica Merlot', 'vino', 'Atómica Wines', 'Merlot', 'Mendoza, Argentina', 2022, 'Merlot suave con aromas de ciruela y chocolate.', 3800.00, 22, NULL, 1, NOW(), NOW(), 1),
('ROSÉ-SANTA-750', 'Santa Rosé de Malbec', 'vino', 'Bodegas Santa', 'Malbec', 'Mendoza, Argentina', 2023, 'Rosado pálido y refrescante, ideal para primavera y verano.', 3200.00, 28, NULL, 1, NOW(), NOW(), 1),
('BLEND-TAMA-750', 'Tamajón Red Blend', 'vino', 'Tamajón', 'Malbec-Cabernet', 'Mendoza, Argentina', 2021, 'Blend armónico que combina lo mejor de dos variedades nobles.', 5500.00, 17, NULL, 1, NOW(), NOW(), 1),
('ESPUMANTE-CHANDON-750', 'Chandon Classic Brut', 'espumante', 'Bodega Chandon', NULL, 'Mendoza, Argentina', 2023, 'Espumante clásico con burbujas finas y notas cítricas. Perfecto para celebraciones.', 4500.00, 35, NULL, 1, NOW(), NOW(), 1),
('ESPUMANTE-PEÑAFLOR-750', 'Peñaflor Brut Nature', 'espumante', 'Bodega Peñaflor', NULL, 'Mendoza, Argentina', 2023, 'Espumante seco y mineral con carácter elegante.', 3800.00, 28, NULL, 1, NOW(), NOW(), 1),
('ESPUMANTE-TRUMP-750', 'Trump Tinto Brut', 'espumante', 'Bodega Trump', NULL, 'San Juan, Argentina', 2022, 'Espumante tinto con complejidad y frescura.', 4200.00, 20, NULL, 1, NOW(), NOW(), 1),
('ESPUMANTE-RENACER-750', 'Renacer Rosé Brut', 'espumante', 'Bodega Renacer', NULL, 'La Pampa, Argentina', 2023, 'Espumante rosado con aromas a frutos berries.', 3900.00, 25, NULL, 1, NOW(), NOW(), 1),
('WHISKY-AUCHENTOSHAN-700', 'Auchentoshan Three Wood', 'whisky', 'Auchentoshan Distillery', NULL, 'Escocia', NULL, 'Whisky escocés triple destilado con notas de roble y frutas maduras.', 12000.00, 8, NULL, 1, NOW(), NOW(), 1),
('WHISKY-GLENMORANGIE-700', 'Glenmorangie The Original', 'whisky', 'Glenmorangie Distillery', NULL, 'Escocia', NULL, 'Whisky Highland clásico con 10 años de envejecimiento. Suave y aromático.', 10500.00, 10, NULL, 1, NOW(), NOW(), 1),
('WHISKY-OBAN-700', 'Oban 14 Years Old', 'whisky', 'Oban Distillery', NULL, 'Escocia', NULL, 'Whisky de los Highlands con carácter robusto y ahumado.', 13500.00, 6, NULL, 1, NOW(), NOW(), 1),
('WHISKY-HIGHLAND-700', 'Highland Park 18', 'whisky', 'Highland Park Distillery', NULL, 'Escocia', NULL, 'Whisky Islay con equilibrio perfecto entre turbación y dulzura.', 15000.00, 5, NULL, 1, NOW(), NOW(), 1),
('GIN-HENDRICKS-700', 'Hendrick\'s Gin', 'gin', 'Hendrick\'s Distillery', NULL, 'Escocia', NULL, 'Gin premium infusionado con pepino y especias. Tónica es esencial.', 9000.00, 12, NULL, 1, NOW(), NOW(), 1),
('GIN-TANQUERAY-700', 'Tanqueray London Dry', 'gin', 'Tanqueray Distillery', NULL, 'Inglaterra', NULL, 'Gin clásico London Dry con junípero prominente y sabor seco.', 7500.00, 18, NULL, 1, NOW(), NOW(), 1),
('GIN-BOMBAY-700', 'Bombay Sapphire', 'gin', 'Bombay Distillery', NULL, 'Inglaterra', NULL, 'Gin premium con 10 botánicos diferentes. Color azul característico.', 8500.00, 15, NULL, 1, NOW(), NOW(), 1),
('GIN-GORDON-700', 'Gordon\'s London Dry', 'gin', 'Gordon\'s Distillery', NULL, 'Inglaterra', NULL, 'Gin tradicional con sabor a botánicos clásicos, ideal para martinis.', 6800.00, 20, NULL, 1, NOW(), NOW(), 1),
('LICOR-BAILEYS-750', 'Baileys Irish Cream', 'licor', 'Baileys', NULL, 'Irlanda', NULL, 'Licor cremoso con chocolate e whisky. Perfecto para postres.', 5200.00, 22, NULL, 1, NOW(), NOW(), 1),
('LICOR-KAHLUA-750', 'Kahlúa Original', 'licor', 'Kahlúa', NULL, 'México', NULL, 'Licor de café mexicano con dulzura y cuerpo completo.', 5900.00, 18, NULL, 1, NOW(), NOW(), 1),
('LICOR-AMARETTO-750', 'Amaretto di Saronno', 'licor', 'Saronno', NULL, 'Italia', NULL, 'Licor de almendra italiana con aroma delicado y sabor suave.', 4800.00, 16, NULL, 1, NOW(), NOW(), 1),
('LICOR-COINTREAU-750', 'Cointreau', 'licor', 'Cointreau', NULL, 'Francia', NULL, 'Licor de naranja de clase mundial, ingrediente de cócteles clásicos.', 7200.00, 11, NULL, 1, NOW(), NOW(), 1),
('CERVEZA-QUILMES-473', 'Quilmes Clásica', 'cerveza', 'Cervecería Quilmes', NULL, 'Argentina', NULL, 'Cerveza rubia ligera y refrescante, la marca argentina por excelencia.', 450.00, 100, NULL, 1, NOW(), NOW(), 1),
('CERVEZA-STELLA-500', 'Stella Artois', 'cerveza', 'Stella Artois', NULL, 'Bélgica', NULL, 'Cerveza pilsen belga premium con 600 años de tradición.', 850.00, 45, NULL, 1, NOW(), NOW(), 1),
('CERVEZA-CORONA-355', 'Corona Extra', 'cerveza', 'Corona', NULL, 'México', NULL, 'Cerveza mexicana clara y crujiente, tradicional con limón.', 650.00, 60, NULL, 1, NOW(), NOW(), 1),
('CERVEZA-HEINEKEN-500', 'Heineken Premium', 'cerveza', 'Heineken', NULL, 'Holanda', NULL, 'Cerveza holandesa con calidad consistente y sabor balanceado.', 750.00, 55, NULL, 1, NOW(), NOW(), 1),
('CERVEZA-IPA-ANTARES-473', 'Antares IPA', 'cerveza', 'Cervecería Antares', NULL, 'Argentina', NULL, 'India Pale Ale de lúpulo pronunciado con amargor característico.', 600.00, 30, NULL, 1, NOW(), NOW(), 1),
('MALBEC-DECERO-750', 'Decero Malbec', 'vino', 'Bodegas Decero', 'Malbec', 'Mendoza, Argentina', 2022, 'Malbec moderno con expresión pura de la variedad y terroir.', 7500.00, 14, NULL, 1, NOW(), NOW(), 1),
('VINO-MALAMADRE-750', 'Mala Madre Rojo', 'vino', 'Mala Madre', 'Blend', 'Río Negro, Argentina', 2021, 'Blend joven y atrevido con personalidad propia y precio accesible.', 2800.00, 26, NULL, 1, NOW(), NOW(), 1),
('VINO-RIGLOS-750', 'Riglos Premium Red', 'vino', 'Bodega Riglos', 'Malbec', 'San Juan, Argentina', 2020, 'Vino de valor excepcional con calidad de bodega grande.', 3400.00, 24, NULL, 1, NOW(), NOW(), 1),
('ESPUMANTE-EXTRA-BRUT-750', 'Finca Pedregal Extra Brut', 'espumante', 'Finca Pedregal', NULL, 'Mendoza, Argentina', 2022, 'Espumante ultra seco para paladares más sofisticados.', 5100.00, 19, NULL, 1, NOW(), NOW(), 1),
('GIN-NACIONAL-ANCHO-700', 'Ancho Gin Nacional', 'gin', 'Destilería Ancho', NULL, 'Argentina', NULL, 'Gin argentino artesanal con botánicos locales.', 8200.00, 14, NULL, 1, NOW(), NOW(), 1),
('LICOR-JÄGERMEISTER-700', 'Jägermeister', 'licor', 'Jägermeister', NULL, 'Alemania', NULL, 'Licor digestivo con 56 botánicos. Tradicional tomarse congelado.', 4500.00, 20, NULL, 1, NOW(), NOW(), 1),
('CERVEZA-BRAHMA-473', 'Brahma', 'cerveza', 'Brahma', NULL, 'Brasil', NULL, 'Cerveza brasileña con carácter suave y refrescante.', 500.00, 80, NULL, 1, NOW(), NOW(), 1),
('VINO-TINTO-SANTA-RITA-750', 'Santa Rita Casa Real Merlot', 'vino', 'Bodega Santa Rita', 'Merlot', 'Aconcagua Valley, Chile', 2021, 'Merlot chileno con perfil frutal marcado y taninos suaves.', 6800.00, 11, NULL, 1, NOW(), NOW(), 1),
('WHISKY-JOHNNIE-WALKER-700', 'Johnnie Walker Red Label', 'whisky', 'Johnnie Walker', NULL, 'Escocia', NULL, 'Blended Scotch Whisky accesible con carácter ahumado.', 9500.00, 13, NULL, 1, NOW(), NOW(), 1);

-- =====================================================
-- promotions (20 promociones sin end_at)
-- =====================================================
INSERT INTO promotions (
    product_id, promotion_type, parameter_value, visible_text, start_at, end_at, is_active, created_by_admin_id, created_at, updated_at
) VALUES
(1, 'porcentaje', 15.00, '15% OFF en Malbec Álamos', NOW(), NULL, 1, 1, NOW(), NOW()),
(2, 'precio_fijo', 3800.00, 'Pinot Santa a $3800', NOW(), NULL, 1, 1, NOW(), NOW()),
(3, '2x1', 0.00, '2x1 en Cabernet Norton', NOW(), NULL, 1, 1, NOW(), NOW()),
(4, 'porcentaje', 10.00, '10% OFF Chardonnay Catena', NOW(), NULL, 1, 1, NOW(), NOW()),
(5, 'precio_fijo', 5800.00, 'Syrah Achaval a $5800', NOW(), NULL, 1, 1, NOW(), NOW()),
(6, '3x2', 0.00, '3x2 en Susana Balbo Signature', NOW(), NULL, 1, 1, NOW(), NOW()),
(11, 'porcentaje', 20.00, '20% OFF Champagne Chandon', NOW(), NULL, 1, 1, NOW(), NOW()),
(15, 'precio_fijo', 11000.00, 'Auchentoshan a $11000', NOW(), NULL, 1, 1, NOW(), NOW()),
(19, '2x1', 0.00, '2x1 en Hendrick\'s Gin', NOW(), NULL, 1, 1, NOW(), NOW()),
(22, 'porcentaje', 12.00, '12% OFF Baileys Irish Cream', NOW(), NULL, 1, 1, NOW(), NOW()),
(26, 'precio_fijo', 9200.00, 'Quilmes caja x10 a $4500', NOW(), NULL, 1, 1, NOW(), NOW()),
(31, 'porcentaje', 18.00, '18% OFF Decero Malbec', NOW(), NULL, 1, 1, NOW(), NOW()),
(32, '3x2', 0.00, '3x2 en Mala Madre Tinto', NOW(), NULL, 1, 1, NOW(), NOW()),
(33, 'porcentaje', 14.00, '14% OFF Riglos Premium', NOW(), NULL, 1, 1, NOW(), NOW()),
(34, 'precio_fijo', 4600.00, 'Espumante Finca Pedregal a $4600', NOW(), NULL, 1, 1, NOW(), NOW()),
(35, '2x1', 0.00, '2x1 en Ancho Gin', NOW(), NULL, 1, 1, NOW(), NOW()),
(36, 'porcentaje', 16.00, '16% OFF Jägermeister', NOW(), NULL, 1, 1, NOW(), NOW()),
(37, 'precio_fijo', 7200.00, 'Santa Rita Casa Real a $7200', NOW(), NULL, 1, 1, NOW(), NOW()),
(38, '3x2', 0.00, '3x2 en Johnnie Walker Red', NOW(), NULL, 1, 1, NOW(), NOW()),
(9, 'porcentaje', 13.00, '13% OFF en Luigi Bosca Bonarda', NOW(), NULL, 1, 1, NOW(), NOW());

-- =====================================================
-- consult_events (eventos de consulta realistas - últimos 30 días)
-- =====================================================
INSERT INTO consult_events (product_id, occurred_at, channel) VALUES
(1, NOW(), 'QR', NULL),
(1, DATE_SUB(NOW(), INTERVAL 2 HOUR), 'BUSQUEDA', NULL),
(2, DATE_SUB(NOW(), INTERVAL 4 HOUR), 'QR', NULL),
(3, DATE_SUB(NOW(), INTERVAL 8 HOUR), 'BUSQUEDA', NULL),
(4, DATE_SUB(NOW(), INTERVAL 1 DAY), 'QR', NULL),
(5, DATE_SUB(NOW(), INTERVAL 1 DAY), 'BUSQUEDA', NULL),
(6, DATE_SUB(NOW(), INTERVAL 2 DAY), 'QR', NULL),
(7, DATE_SUB(NOW(), INTERVAL 2 DAY), 'BUSQUEDA', NULL),
(8, DATE_SUB(NOW(), INTERVAL 3 DAY), 'QR', NULL),
(9, DATE_SUB(NOW(), INTERVAL 3 DAY), 'BUSQUEDA', NULL),
(10, DATE_SUB(NOW(), INTERVAL 4 DAY), 'QR', NULL),
(11, DATE_SUB(NOW(), INTERVAL 4 DAY), 'BUSQUEDA', NULL),
(11, DATE_SUB(NOW(), INTERVAL 5 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 5 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 6 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 6 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 7 DAY), 'QR', NULL),
(16, DATE_SUB(NOW(), INTERVAL 8 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 8 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 9 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 10 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 10 DAY), 'BUSQUEDA', NULL),
(21, DATE_SUB(NOW(), INTERVAL 11 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 12 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 12 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 13 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 14 DAY), 'QR', NULL),
(26, DATE_SUB(NOW(), INTERVAL 14 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 15 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 16 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 16 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 17 DAY), 'BUSQUEDA', NULL),
(1, DATE_SUB(NOW(), INTERVAL 18 DAY), 'QR', NULL),
(1, DATE_SUB(NOW(), INTERVAL 19 DAY), 'BUSQUEDA', NULL),
(2, DATE_SUB(NOW(), INTERVAL 20 DAY), 'QR', NULL),
(3, DATE_SUB(NOW(), INTERVAL 21 DAY), 'BUSQUEDA', NULL),
(4, DATE_SUB(NOW(), INTERVAL 22 DAY), 'QR', NULL),
(5, DATE_SUB(NOW(), INTERVAL 23 DAY), 'BUSQUEDA', NULL),
(6, DATE_SUB(NOW(), INTERVAL 24 DAY), 'QR', NULL),
(7, DATE_SUB(NOW(), INTERVAL 25 DAY), 'BUSQUEDA', NULL),
(11, DATE_SUB(NOW(), INTERVAL 26 DAY), 'QR', NULL),
(11, DATE_SUB(NOW(), INTERVAL 27 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 28 DAY), 'QR', NULL),
(19, DATE_SUB(NOW(), INTERVAL 29 DAY), 'BUSQUEDA', NULL),
(22, DATE_SUB(NOW(), INTERVAL 30 DAY), 'QR', NULL),
(26, DATE_SUB(NOW(), INTERVAL 30 DAY), 'BUSQUEDA', NULL);
(1, DATE_SUB(NOW(), INTERVAL 89 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 89 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 89 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 89 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 89 DAY), 'QR', NULL),
-- Día 2
(6, DATE_SUB(NOW(), INTERVAL 88 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 88 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 88 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 88 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 88 DAY), 'BUSQUEDA', NULL),
-- Día 3
(11, DATE_SUB(NOW(), INTERVAL 87 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 87 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 87 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 87 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 87 DAY), 'QR', NULL),
-- Día 4
(16, DATE_SUB(NOW(), INTERVAL 86 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 86 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 86 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 86 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 86 DAY), 'BUSQUEDA', NULL),
-- Día 5
(21, DATE_SUB(NOW(), INTERVAL 85 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 85 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 85 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 85 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 85 DAY), 'QR', NULL),
-- Día 6
(26, DATE_SUB(NOW(), INTERVAL 84 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 84 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 84 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 84 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 84 DAY), 'BUSQUEDA', NULL),
-- Día 7
(1, DATE_SUB(NOW(), INTERVAL 83 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 83 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 83 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 83 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 83 DAY), 'QR', NULL),
-- Día 8
(6, DATE_SUB(NOW(), INTERVAL 82 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 82 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 82 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 82 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 82 DAY), 'BUSQUEDA', NULL),
-- Día 9
(11, DATE_SUB(NOW(), INTERVAL 81 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 81 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 81 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 81 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 81 DAY), 'QR', NULL),
-- Día 10
(16, DATE_SUB(NOW(), INTERVAL 80 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 80 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 80 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 80 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 80 DAY), 'BUSQUEDA', NULL),
-- Día 11
(21, DATE_SUB(NOW(), INTERVAL 79 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 79 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 79 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 79 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 79 DAY), 'QR', NULL),
-- Día 12
(26, DATE_SUB(NOW(), INTERVAL 78 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 78 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 78 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 78 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 78 DAY), 'BUSQUEDA', NULL),
-- Día 13
(1, DATE_SUB(NOW(), INTERVAL 77 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 77 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 77 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 77 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 77 DAY), 'QR', NULL),
-- Día 14
(6, DATE_SUB(NOW(), INTERVAL 76 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 76 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 76 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 76 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 76 DAY), 'BUSQUEDA', NULL),
-- Día 15
(11, DATE_SUB(NOW(), INTERVAL 75 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 75 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 75 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 75 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 75 DAY), 'QR', NULL),
-- Día 16
(16, DATE_SUB(NOW(), INTERVAL 74 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 74 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 74 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 74 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 74 DAY), 'BUSQUEDA', NULL),
-- Día 17
(21, DATE_SUB(NOW(), INTERVAL 73 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 73 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 73 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 73 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 73 DAY), 'QR', NULL),
-- Día 18
(26, DATE_SUB(NOW(), INTERVAL 72 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 72 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 72 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 72 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 72 DAY), 'BUSQUEDA', NULL),
-- Día 19
(1, DATE_SUB(NOW(), INTERVAL 71 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 71 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 71 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 71 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 71 DAY), 'QR', NULL),
-- Día 20
(6, DATE_SUB(NOW(), INTERVAL 70 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 70 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 70 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 70 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 70 DAY), 'BUSQUEDA', NULL),
-- Día 21
(11, DATE_SUB(NOW(), INTERVAL 69 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 69 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 69 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 69 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 69 DAY), 'QR', NULL),
-- Día 22
(16, DATE_SUB(NOW(), INTERVAL 68 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 68 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 68 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 68 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 68 DAY), 'BUSQUEDA', NULL),
-- Día 23
(21, DATE_SUB(NOW(), INTERVAL 67 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 67 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 67 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 67 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 67 DAY), 'QR', NULL),
-- Día 24
(26, DATE_SUB(NOW(), INTERVAL 66 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 66 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 66 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 66 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 66 DAY), 'BUSQUEDA', NULL),
-- Día 25
(1, DATE_SUB(NOW(), INTERVAL 65 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 65 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 65 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 65 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 65 DAY), 'QR', NULL),
-- Día 26
(6, DATE_SUB(NOW(), INTERVAL 64 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 64 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 64 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 64 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 64 DAY), 'BUSQUEDA', NULL),
-- Día 27
(11, DATE_SUB(NOW(), INTERVAL 63 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 63 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 63 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 63 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 63 DAY), 'QR', NULL),
-- Día 28
(16, DATE_SUB(NOW(), INTERVAL 62 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 62 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 62 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 62 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 62 DAY), 'BUSQUEDA', NULL),
-- Día 29
(21, DATE_SUB(NOW(), INTERVAL 61 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 61 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 61 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 61 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 61 DAY), 'QR', NULL),
-- Día 30
(26, DATE_SUB(NOW(), INTERVAL 60 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 60 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 60 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 60 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 60 DAY), 'BUSQUEDA', NULL),
-- Día 31
(1, DATE_SUB(NOW(), INTERVAL 59 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 59 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 59 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 59 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 59 DAY), 'QR', NULL),
-- Día 32
(6, DATE_SUB(NOW(), INTERVAL 58 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 58 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 58 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 58 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 58 DAY), 'BUSQUEDA', NULL),
-- Día 33
(11, DATE_SUB(NOW(), INTERVAL 57 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 57 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 57 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 57 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 57 DAY), 'QR', NULL),
-- Día 34
(16, DATE_SUB(NOW(), INTERVAL 56 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 56 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 56 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 56 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 56 DAY), 'BUSQUEDA', NULL),
-- Día 35
(21, DATE_SUB(NOW(), INTERVAL 55 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 55 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 55 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 55 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 55 DAY), 'QR', NULL),
-- Día 36
(26, DATE_SUB(NOW(), INTERVAL 54 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 54 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 54 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 54 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 54 DAY), 'BUSQUEDA', NULL),
-- Día 37
(1, DATE_SUB(NOW(), INTERVAL 53 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 53 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 53 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 53 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 53 DAY), 'QR', NULL),
-- Día 38
(6, DATE_SUB(NOW(), INTERVAL 52 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 52 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 52 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 52 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 52 DAY), 'BUSQUEDA', NULL),
-- Día 39
(11, DATE_SUB(NOW(), INTERVAL 51 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 51 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 51 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 51 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 51 DAY), 'QR', NULL),
-- Día 40
(16, DATE_SUB(NOW(), INTERVAL 50 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 50 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 50 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 50 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 50 DAY), 'BUSQUEDA', NULL),
-- Día 41
(21, DATE_SUB(NOW(), INTERVAL 49 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 49 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 49 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 49 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 49 DAY), 'QR', NULL),
-- Día 42
(26, DATE_SUB(NOW(), INTERVAL 48 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 48 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 48 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 48 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 48 DAY), 'BUSQUEDA', NULL),
-- Día 43
(1, DATE_SUB(NOW(), INTERVAL 47 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 47 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 47 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 47 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 47 DAY), 'QR', NULL),
-- Día 44
(6, DATE_SUB(NOW(), INTERVAL 46 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 46 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 46 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 46 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 46 DAY), 'BUSQUEDA', NULL),
-- Día 45
(11, DATE_SUB(NOW(), INTERVAL 45 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 45 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 45 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 45 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 45 DAY), 'QR', NULL),
-- Día 46
(16, DATE_SUB(NOW(), INTERVAL 44 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 44 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 44 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 44 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 44 DAY), 'BUSQUEDA', NULL),
-- Día 47
(21, DATE_SUB(NOW(), INTERVAL 43 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 43 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 43 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 43 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 43 DAY), 'QR', NULL),
-- Día 48
(26, DATE_SUB(NOW(), INTERVAL 42 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 42 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 42 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 42 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 42 DAY), 'BUSQUEDA', NULL),
-- Día 49
(1, DATE_SUB(NOW(), INTERVAL 41 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 41 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 41 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 41 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 41 DAY), 'QR', NULL),
-- Día 50
(6, DATE_SUB(NOW(), INTERVAL 40 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 40 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 40 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 40 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 40 DAY), 'BUSQUEDA', NULL),
-- Día 51
(11, DATE_SUB(NOW(), INTERVAL 39 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 39 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 39 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 39 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 39 DAY), 'QR', NULL),
-- Día 52
(16, DATE_SUB(NOW(), INTERVAL 38 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 38 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 38 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 38 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 38 DAY), 'BUSQUEDA', NULL),
-- Día 53
(21, DATE_SUB(NOW(), INTERVAL 37 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 37 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 37 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 37 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 37 DAY), 'QR', NULL),
-- Día 54
(26, DATE_SUB(NOW(), INTERVAL 36 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 36 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 36 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 36 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 36 DAY), 'BUSQUEDA', NULL),
-- Día 55
(1, DATE_SUB(NOW(), INTERVAL 35 DAY), 'QR', NULL),
(2, DATE_SUB(NOW(), INTERVAL 35 DAY), 'BUSQUEDA', NULL),
(3, DATE_SUB(NOW(), INTERVAL 35 DAY), 'QR', NULL),
(4, DATE_SUB(NOW(), INTERVAL 35 DAY), 'BUSQUEDA', NULL),
(5, DATE_SUB(NOW(), INTERVAL 35 DAY), 'QR', NULL),
-- Día 56
(6, DATE_SUB(NOW(), INTERVAL 34 DAY), 'BUSQUEDA', NULL),
(7, DATE_SUB(NOW(), INTERVAL 34 DAY), 'QR', NULL),
(8, DATE_SUB(NOW(), INTERVAL 34 DAY), 'BUSQUEDA', NULL),
(9, DATE_SUB(NOW(), INTERVAL 34 DAY), 'QR', NULL),
(10, DATE_SUB(NOW(), INTERVAL 34 DAY), 'BUSQUEDA', NULL),
-- Día 57
(11, DATE_SUB(NOW(), INTERVAL 33 DAY), 'QR', NULL),
(12, DATE_SUB(NOW(), INTERVAL 33 DAY), 'BUSQUEDA', NULL),
(13, DATE_SUB(NOW(), INTERVAL 33 DAY), 'QR', NULL),
(14, DATE_SUB(NOW(), INTERVAL 33 DAY), 'BUSQUEDA', NULL),
(15, DATE_SUB(NOW(), INTERVAL 33 DAY), 'QR', NULL),
-- Día 58
(16, DATE_SUB(NOW(), INTERVAL 32 DAY), 'BUSQUEDA', NULL),
(17, DATE_SUB(NOW(), INTERVAL 32 DAY), 'QR', NULL),
(18, DATE_SUB(NOW(), INTERVAL 32 DAY), 'BUSQUEDA', NULL),
(19, DATE_SUB(NOW(), INTERVAL 32 DAY), 'QR', NULL),
(20, DATE_SUB(NOW(), INTERVAL 32 DAY), 'BUSQUEDA', NULL),
-- Día 59
(21, DATE_SUB(NOW(), INTERVAL 31 DAY), 'QR', NULL),
(22, DATE_SUB(NOW(), INTERVAL 31 DAY), 'BUSQUEDA', NULL),
(23, DATE_SUB(NOW(), INTERVAL 31 DAY), 'QR', NULL),
(24, DATE_SUB(NOW(), INTERVAL 31 DAY), 'BUSQUEDA', NULL),
(25, DATE_SUB(NOW(), INTERVAL 31 DAY), 'QR', NULL),
-- Día 60
(26, DATE_SUB(NOW(), INTERVAL 30 DAY), 'BUSQUEDA', NULL),
(27, DATE_SUB(NOW(), INTERVAL 30 DAY), 'QR', NULL),
(28, DATE_SUB(NOW(), INTERVAL 30 DAY), 'BUSQUEDA', NULL),
(29, DATE_SUB(NOW(), INTERVAL 30 DAY), 'QR', NULL),
(30, DATE_SUB(NOW(), INTERVAL 30 DAY), 'BUSQUEDA', NULL);
